### ISSUE TITLE
Does not play nice with bullet threading

### ISSUE THREAD

**Issue by nmartin84** [nmartin84/admonition-panels#1]

**Comment by sbwcwso** [comment]
Yead, the left block line is broken whick is very ugly.

![屏幕截图 2022-09-12 094344](https://user-images.githubusercontent.com/48000576/189560012-e5cb3e7b-1dde-49c5-9f0d-39066802799d.jpg)

**Comment by nmartin84** [comment]
@sbwcwso - that's on my list to fix here soon, the styling gets a little funky when you start adding child blocks. I should have that fixed soon though. Thanks for sharing!

**Comment by oriofdarkforest** [comment]
![image](https://user-images.githubusercontent.com/72719841/190573561-97834d84-feeb-431b-9463-7dea88a566d4.png)
Does it have any theme requirement? Seems not working correctly for my Woz Theme.

**Comment by dismory** [comment]
> ![image](https://user-images.githubusercontent.com/72719841/190573561-97834d84-feeb-431b-9463-7dea88a566d4.png)
> Does it have any theme requirement? Seems not working correctly for my Woz Theme.

Same visual issue here, also with Woz Theme.

**Comment by nmartin84** [comment]
@oriofdarkforest @dismory - yeah I can reproduce the issue, this would have something to do with the Woz theme itself, but let me take a look and see how I can fix this. I'll post a reply when a fix is pushed.

**Comment by YU000jp** [comment]
Temporarily. Removed background color. I changed the border to the right side.
![image](https://user-images.githubusercontent.com/111847207/191926529-f1809ebc-70d6-4b34-bbd7-99c7f8125d47.png)

It may be difficult to add a background color and border there. Does not match bullet nests.


https://github.com/YU000jp/admonition-panels/releases/tag/0.0.1

**Comment by nmartin84** [comment]
I just pushed a fix to address the woz theme issues. Give it a try and let me know if you still have any issues @dismory @oriofdarkforest .

**Comment by nmartin84** [comment]
@YU000jp I have another approach i'm going to use to disable bullet threading for panels. Time permitted I should have something ready this weekend.

**Comment by dismory** [comment]
> I just pushed a fix to address the woz theme issues. Give it a try and let me know if you still have any issues @dismory @oriofdarkforest .

The bug is still there using Woz Theme with Bullet Threading plugin enabled.

It looks normal using Woz Theme with Bullet Threading plugin disabled, however, icon before title of panel missed. What's more, the left border has a little gap if the block has only one child.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/142608/192095405-b8ee6875-fee4-4f78-90b1-b9e922b71463.png">

**Comment by 0w0miki** [comment]
> ![image](https://user-images.githubusercontent.com/72719841/190573561-97834d84-feeb-431b-9463-7dea88a566d4.png) Does it have any theme requirement? Seems not working correctly for my Woz Theme.

Meet the same issue. Bullet threading is broken and child's border has an indent.

I make some changes to my `custom.css`. The result looks like:

<img width="716" alt="图片" src="https://user-images.githubusercontent.com/18544315/193743510-20fa7fad-a403-4938-81a2-b4345c73901a.png">

```css
/* === Admonition fix === */
:is(.content > .blocks-container) .ls-block[data-refs-self*='admon-'][haschild] .block-body {
  margin-bottom: 0 !important;
  padding-bottom: 0 !important;
  border-radius: 0 !important;
}
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children {
  margin-bottom: 10px;
}

/* Background fix */
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children > .ls-block > .flex {
  border-left: 0;
  background-color: transparent !important;
}
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container::before {
  content: "";
  border-left: solid 4px;
  position: absolute;
  left: 15px; /* 17px(margin-left) - 4px(border-width) / 2 */
  right: 8px; /* same as margin-right of context block */
  height: 100%;
  border-bottom-left-radius: 2px;
  border-bottom-right-radius: 2px;
  box-shadow: var(--cl-box-shadow);
  background-color: var(--ls-secondary-background-color);
}

[data-refs-self*="admon-lists"] > .block-children-container::before {
  border-color: rgb(124, 77, 255) !important;
}
[data-refs-self*="admon-tips"] > .block-children-container::before {
  border-color: rgb(0, 191, 165) !important;
}
[data-refs-self*="admon-warning"] > .block-children-container::before {
  border-color: rgb(255, 145, 0) !important;
}
[data-refs-self*="admon-info"] > .block-children-container::before {
  border-color: rgb(0, 184, 212) !important;
}
[data-refs-self*="admon-success"] > .block-children-container::before {
  border-color: rgb(0, 200, 83) !important;
}
[data-refs-self*="admon-failure"] > .block-children-container::before {
  border-color: rgb(255, 82, 82) !important;
}
[data-refs-self*="admon-danger"] > .block-children-container::before {
  border-color: rgb(255, 23, 68) !important;
}
[data-refs-self*="admon-bug"] > .block-children-container::before {
  border-color: rgb(245, 0, 87) !important;
}
[data-refs-self*="admon-quote"] > .block-children-container::before {
  border-color: rgb(158, 158, 158) !important;
}

/* Bullet threading fix */
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children > .ls-block > div > div.items-center::before {
  left: calc(var(--ls-block-bullet-threading-width) * -1 - 17px);
}
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children > .ls-block[haschild] > div > .block-content-wrapper::before {
  left: calc(-15px + 8px);
}

/* Move grandchildren-container lefter */
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children > div[haschild] > .block-children-container {
  padding-left: 17px;
}

/* Dummy border */
:is(.content > .blocks-container) .ls-block[data-refs-self*="admon-"] > .block-children-container > .block-children {
  border-color: transparent;
}

```

**Comment by 0w0miki** [comment]
BTW, the child block in the illustration in README looks separate from the admonition block. Is there any design change? If not, these guys https://github.com/nmartin84/admonition-panels/issues/1#issuecomment-1243116724 https://github.com/nmartin84/admonition-panels/issues/1#issuecomment-1248979591 found the bug.
